In [1]:
import jax
import jax.numpy as jnp
from function_utils import construct_func_from_intensity_matrix
from function_utils import construct_func_from_payment_matrix
from probability_callbacks import ProbabilityCallbacks
from semimarkov_solver import semimarkov_solver

jax.config.update('jax_enable_x64', True)

In [15]:
@jax.jit
def mu_1(t, u):
    return t * 0 + 0 * u + 0.15 * (t < 1 / 12)

@jax.jit
def mu_2(t, u):
    return 1.2 * jnp.exp(-0.05 * t + u * 0) * 0.25

@jax.jit
def unit_payment(t, u):
    return 0 * t + 0 * u * 0 + 1

In [22]:
intensity_matrix = [
    [None, mu_1, None],
    [None, None, None],
    [None, None, None]
]

cf_matrix = [
    [None, None, None],
    [None, unit_payment, None],
    [None, None, None]
]

intensity = construct_func_from_intensity_matrix(intensity_matrix)
cashflow = construct_func_from_payment_matrix(cf_matrix)

u = jnp.concatenate([
    jnp.arange(0, 1, 1 / 12),
    jnp.arange(1, 2, 1 / 24),
    jnp.arange(2, 5, 1 / 12),
    jnp.arange(5, 30 + 1, 1)
])

u = jnp.expand_dims(u, axis=0) + jnp.expand_dims(jnp.arange(0, 1, 0.1), axis=1)

In [23]:
result = semimarkov_solver(grid=u,
                           intensity=intensity,
                           cashflow=cashflow,
                           prob_callback='none',
                           cashflow_callback='default')

In [25]:
0.15 / 12 * 30

0.37499999999999994

In [24]:
jnp.sum(result['cashflow'][0,1])

Array(0.37213867, dtype=float64)

In [13]:
jnp.trapezoid(y=result['probability'], dx=jnp.diff(u[0]))

Array([6.61020213, 6.61020213, 6.61020213, 6.61020213, 6.61020213,
       6.61020213, 6.61020213, 6.61020213, 6.61020213, 6.61020213],      dtype=float64)

In [15]:
result['probability'][0,0,1:] * jnp.diff(u[0])

Array([0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 ,
       0.0078125 , 0.0078125 , 0.0078125 , 0.0078125 , 0.00781

In [6]:
jnp.sum(result['cashflow'][0,0])

Array(861.5, dtype=float64)

In [7]:
result['cashflow'][0,0,:]

Array([ 1.        ,  1.0078125 ,  1.015625  ,  1.0234375 ,  1.03125   ,
        1.0390625 ,  1.046875  ,  1.0546875 ,  1.0625    ,  1.0703125 ,
        1.078125  ,  1.0859375 ,  1.09375   ,  1.1015625 ,  1.109375  ,
        1.1171875 ,  1.125     ,  1.1328125 ,  1.140625  ,  1.1484375 ,
        1.15625   ,  1.1640625 ,  1.171875  ,  1.1796875 ,  1.1875    ,
        1.1953125 ,  1.203125  ,  1.2109375 ,  1.21875   ,  1.2265625 ,
        1.234375  ,  1.2421875 ,  1.25      ,  1.2578125 ,  1.265625  ,
        1.2734375 ,  1.28125   ,  1.2890625 ,  1.296875  ,  1.3046875 ,
        1.3125    ,  1.3203125 ,  1.328125  ,  1.3359375 ,  1.34375   ,
        1.3515625 ,  1.359375  ,  1.3671875 ,  1.375     ,  1.3828125 ,
        1.390625  ,  1.3984375 ,  1.40625   ,  1.4140625 ,  1.421875  ,
        1.4296875 ,  1.4375    ,  1.4453125 ,  1.453125  ,  1.4609375 ,
        1.46875   ,  1.4765625 ,  1.484375  ,  1.4921875 ,  1.5       ,
        1.5078125 ,  1.515625  ,  1.5234375 ,  1.53125   ,  1.53

In [ ]:
result[0][..., 0, :] + result[1][]

(10, 3, 214)

In [ ]:
cashflow_test = [
    [None, None, unit_payment],
    [None, unit_payment, None],
    [None, None, unit_payment]
]

In [ ]:
cashtest = construct_func_from_payment_matrix(cashflow_test)

In [ ]:
intensity_matrix = [
    [None, mu_1, mu_1],
    [None, None, mu_1],
    [mu_1, None, None]
]

flow = construct_func_from_intensity_matrix(intensity_matrix)

u = jnp.concatenate([
    jnp.arange(0, 1, 1 / 128),
    jnp.arange(1, 2, 1 / 24),
    jnp.arange(2, 5, 1 / 12),
    jnp.arange(5, 30 + 1, 1)
])

u = jnp.expand_dims(u, axis=0) + jnp.expand_dims(jnp.arange(0, 1, 0.002), axis=1)

In [ ]:
ProbabilityCallbacks.from_str(None)

<PjitFunction of <function ProbabilityCallbacks.default at 0x7fd01d697600>>

In [ ]:
flow(0, jnp.zeros((10, 1)))

(Array([[[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]],
 
        [[0.3 ],
         [0.15],
         [0.15]]], dtype=float64),
 Array([[[[0.  ],
          [0.  ],
          [0.15]],
 
         [[0.15],
          [0.  ],
          [0.  ]],
 
         [[0.15],
          [0.15],
          [0.  ]]],
 
 
        [[[0.  ],
          [0.  ],
          [0.15]],
 
         [[0.15],
          [0.  ],
          [0.  ]],
 
         [[0.15],
          [0.15],
          [0.  ]]],
 
 
        [[[0.  ],
          [0.  ],
          [0.15]],
 
         [[0.15],
          [0.  ],
    

In [ ]:
p, p_point = semimarkov_solver(u, flow)

In [ ]:
%timeit -r 1 -n 100 semimarkov_solver(u, flow)

95.6 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
